from importlib.resources import files

TEST_RESOURCE_PATH = files('tests._resources')

TEST_API_RESOURCE_PATH = TEST_RESOURCE_PATH.joinpath('api')
TEST_DB_RESOURCE_PATH = TEST_RESOURCE_PATH.joinpath('db')
TEST_EVENT_RESOURCE_PATH = TEST_RESOURCE_PATH.joinpath('events')

TEST_VERIFICATION_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'
