name: Dev Push
on:
  push:
    branches:
      - dev
    paths:
      - '**.py'
      - '**.yml'
      - 'Dockerfile'
      - 'pyproject.toml'

jobs:
  main:
    name: Build Image, Push to ECR, Apply Terraform Plan, Raise PR
    runs-on: ubuntu-latest
    env:
      APP_NAME:              ${{ github.event.repository.name }}
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION:            ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENVIRONMENT:           dev
      GH_PAT:                ${{ secrets.GH_PAT }}
      SHARED_APP_NAME:       expatmagic
      TF_WORKDIR_PREFIX:     apps/${{ github.event.repository.name }}/environments
      TF_REPO:               'adrianmeraz/am-terraform'
    steps:
    - name: Configure AWS credentials
      id:   aws-creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id:     ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ env.AWS_REGION }}

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: ‘2’

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set ECR Repository Url
      env:
        ECR_URL:  ${{ steps.aws-creds.outputs.aws-account-id }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        ECR_NAME: ${{ env.APP_NAME }}-${{ env.ENVIRONMENT }}-ecr
      run: |
        echo "AWS_ECR_REPOSITORY_URL=${{ env.ECR_URL }}/${{ env.ECR_NAME }}" >> $GITHUB_ENV

    - name: Build image, cache layers, and push to ECR
      env:
        REPOSITORY_URL:  ${{ env.AWS_ECR_REPOSITORY_URL }}
        IMAGE_TAG:       "latest"
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        provenance: false # Required per https://stackoverflow.com/a/75149347
        tags: ${{ env.REPOSITORY_URL }}:${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Checkout Terraform Repo
      uses: actions/checkout@v4
      with:
        ref: main
        repository: ${{ env.TF_REPO }}
        token: ${{ env.GH_PAT }}

    - name: Set Terraform Working Directory
      run: |
        echo "TF_WORKDIR=${{ env.TF_WORKDIR_PREFIX }}/${{ env.ENVIRONMENT }}" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.1

    - name: Terraform Init
      working-directory: ${{ env.TF_WORKDIR }}
      id: tf-init
      run: |
        terraform init

    - name: Terraform Apply
      working-directory: ${{ env.TF_WORKDIR }}
      id: tf-apply
      run: |
        terraform apply -auto-approve -input=false -parallelism=50 \
          -var app_name="${{ env.APP_NAME }}" \
          -var aws_access_key="${{ env.AWS_ACCESS_KEY_ID }}" \
          -var aws_region="${{ env.AWS_REGION }}" \
          -var aws_secret_key="${{ env.AWS_SECRET_ACCESS_KEY }}" \
          -var environment="${{ env.ENVIRONMENT }}" \
          -var shared_app_name="${{ env.SHARED_APP_NAME }}"

    - name: Checkout Main Branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Reset main branch
      run: |
        git fetch origin dev:dev
        git reset --hard dev

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        branch: main-promotion
        delete-branch: true
        title: Promote dev to main branch
